<a href="https://colab.research.google.com/github/everestso/Fall24Spring25/blob/main/DeepNetworks_DiamondsInColab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning w/ Diamonds

https://www.kaggle.com/datasets/shivam2503/diamonds

## Provides examples using a variety of Deep Learning APIs

In [1]:
import numpy as np
import pandas as pd

import time

In [2]:
!gdown 1-OzEC9axnc2fTMMcHCXnBkQzypluJLLG

file_name = 'diamonds.csv'

df = pd.read_csv(file_name)

df.head()
print (df.shape)

Downloading...
From: https://drive.google.com/uc?id=1-OzEC9axnc2fTMMcHCXnBkQzypluJLLG
To: /content/diamonds.csv
100% 2.57M/2.57M [00:00<00:00, 160MB/s]
(53940, 10)


In [3]:
#diamond_sample = df.sample(30, random_state=12)
diamond_sample = df.copy()
print(f"{diamond_sample.shape=}")

# Create a dataframe X containing all the features except cut, color, clarity, and price
X = diamond_sample.drop(['cut', 'color', 'clarity', 'price'], axis=1)
print(f"{X.columns=}, {X.shape=}")
print(f"{X[:3]}")


# Create a dataframe y containing the feature price
y = diamond_sample[['price']]
print(f"{y.columns}")
print(f"{y.iloc[:3]=}")

diamond_sample.shape=(53940, 10)
X.columns=Index(['carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object'), X.shape=(53940, 6)
   carat  depth  table     x     y     z
0   0.23   61.5   55.0  3.95  3.98  2.43
1   0.21   59.8   61.0  3.89  3.84  2.31
2   0.23   56.9   65.0  4.05  4.07  2.31
Index(['price'], dtype='object')
y.iloc[:3]=   price
0    326
1    326
2    327


## Transforms

In [4]:
from sklearn.model_selection import train_test_split
# Define a standardization scaler to transform values
from sklearn.preprocessing import StandardScaler

# Split data into train and test sets
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.3, random_state=123)

Transform = StandardScaler()

# Apply scaler
Xtrain_scaled = Transform.fit_transform(Xtrain)
Xtest_scaled = Transform.transform(Xtest)

print  (Xtrain_scaled)

[[ 0.55116139 -0.87705508 -0.20503673  0.79886224  0.74694202  0.64630735]
 [-0.84330851  0.31649342 -1.10028304 -0.87788733 -0.83947701 -0.81830926]
 [-0.82218018 -2.07060358  2.03307906 -0.77086076 -0.77012536 -0.95913778]
 ...
 [-1.05459183  0.24628469 -1.10028304 -1.27923696 -1.22091109 -1.21262911]
 [ 0.4243914   0.80795457 -0.20503673  0.55805246  0.50421124  0.6322245 ]
 [-0.18833022  1.08878951 -0.20503673 -0.07518807 -0.04193302  0.06891042]]


In [5]:
# prompt: Print the transform formula details

print(f"Transform.mean_ = {Transform.mean_}")
print(f"Transform.scale_ = {Transform.scale_}")

print (f"{Xtrain.columns[0]=}, {Transform.mean_[0]=}, {Transform.scale_[0]=}, {np.std(Xtrain[Xtrain.columns[0]])=}")
print (f"{Xtrain.iloc[0,0]=}, {(Xtrain.iloc[0,0]-Transform.mean_[0])/Transform.scale_[0]=}, {Xtrain_scaled[0][0]=}")
print (f"{np.mean(Xtrain, axis=0)=}")
print (f"{np.std(Xtrain, axis=0)=}")

Transform.mean_ = [ 0.79913634 61.74921076 57.45805657  5.73430213  5.73837147  3.54106785]
Transform.scale_ = [0.47329813 1.42432419 2.23402205 1.12121693 1.15354138 0.71008344]
Xtrain.columns[0]='carat', Transform.mean_[0]=0.7991363419672652, Transform.scale_[0]=0.47329813202512444, np.std(Xtrain[Xtrain.columns[0]])=0.47329813202512444
Xtrain.iloc[0,0]=1.06, (Xtrain.iloc[0,0]-Transform.mean_[0])/Transform.scale_[0]=0.5511613935946977, Xtrain_scaled[0][0]=0.5511613935946977
np.mean(Xtrain, axis=0)=carat     0.799136
depth    61.749211
table    57.458057
x         5.734302
y         5.738371
z         3.541068
dtype: float64
np.std(Xtrain, axis=0)=carat    0.473298
depth    1.424324
table    2.234022
x        1.121217
y        1.153541
z        0.710083
dtype: float64


# Now ML Libraries

In [6]:
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [7]:
import os
os.environ["KERAS_BACKEND"] = 'tensorflow'

# The backend must be set before importing keras, not after
import keras
keras.utils.set_random_seed(812)

In [8]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.3)

In [ ]:
# Define the model structure using keras.Sequential. The input layer has shape=(6, ), hidden layer 1 has
# 256 nodes and relu activation, hidden layer 2 had 128 nodes and linear activation, hidden layer 3 has
# 64 nodes and linear activation, and the output layer has 1 node (for regression) and linear activation

# Your code here
model = keras.Sequential([
    keras.layers.Input(shape=(6,)),
    keras.layers.Dense(256, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(1, activation='linear'),
])

print(model.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 256)                 │           1,792 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 128)                 │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │              65 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 43,009 (168.00 KB)

 Trainable params: 43,009 (168.00 KB)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
# Specify training choices using the compile method, with optimizer='Adam', loss='MeanSquaredError',
# metrics='mse'
# Your code here
model.compile(optimizer='Adam', loss='MeanSquaredError', metrics=['mse'])
# Train the model with a batch size of 100, 5 epochs, validation_split=0.1, and verbose=0
# Your code here
model.fit(Xtrain, ytrain, batch_size=100, epochs=130, validation_split=0.1, verbose=0)

predictions = model.predict(Xtest[:3], verbose=0)
print('Predictions:', predictions.round(3))
print('Actual values:', ytest[:3])

Predictions: [[2741.56 ]
 [4768.363]
 [ 994.53 ]]
Actual values:        price
782     2860
10082   4711
32973    811


In [ ]:
out = [(pHat, p) for (pHat, p) in zip(np.ravel(predictions.round(2)), np.ravel(ytest[:3]))]
print (f"{out=}")

out=[(2741.56, 2860), (4768.36, 4711), (994.53, 811)]


In [ ]:
from sklearn.metrics import r2_score

# Assuming 'model' is your trained Keras model, 'Xtest' is your test data, and 'ytest' are the true target values
print (f"{Xtrain.shape=}")
y_predicted = model.predict(Xtrain)
r2 = r2_score(ytrain, y_predicted)
print("R-squared Test:", r2)

y_predicted = model.predict(Xtest)
r2 = r2_score(ytest, y_predicted)
print("R-squared Test:", r2)

Xtrain.shape=(37758, 6)
1180/1180 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step
R-squared Test: 0.8693997039388022
506/506 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
R-squared Test: 0.8681906546274586


# Now pyTorch w/ No Keras


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
status = 10

# Define the model structure using nn.Sequential
model = nn.Sequential(
    nn.Linear(6, 256),
    nn.ReLU(),
    nn.Linear(256, 128),
    nn.ReLU(),
    nn.Linear(128, 64),
    nn.ReLU(),
    nn.Linear(64, 1)
)

# Define the optimizer and loss function
optimizer = optim.Adam(model.parameters())
criterion = nn.MSELoss()

# Convert data to PyTorch tensors
Xtrain_tensor = torch.tensor(Xtrain.values, dtype=torch.float32)
ytrain_tensor = torch.tensor(ytrain.values, dtype=torch.float32)

# Train the model
epochs = 130
batch_size = 100

start_time = time.time()
for epoch in range(epochs):
  for i in range(0, len(Xtrain_tensor), batch_size):
    # Get batch of data
    Xbatch = Xtrain_tensor[i:i+batch_size]
    ybatch = ytrain_tensor[i:i+batch_size]

    # Forward pass
    outputs = model(Xbatch)
    loss = criterion(outputs, ybatch)

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  if ((epoch+1)%10==0):
    end_time = time.time()
    elapsed_time = end_time - start_time
    print(f"Training time ({epoch+1}): {elapsed_time=} seconds")
end_time = time.time()
elapsed_time = end_time - start_time
print(f"Training time ({epoch+1}): {elapsed_time=} seconds")

# Convert test data to PyTorch tensors
Xtest_tensor = torch.tensor(Xtest.values, dtype=torch.float32)

# Make predictions
predictions = model(Xtest_tensor[:3])

# Convert predictions to numpy array
predictions = predictions.detach().numpy()

print('Predictions:', predictions.round(3))
print('Actual values:', ytest[:3])

Predictions: [[2340.513]
 [4241.342]
 [ 830.778]]
Actual values:        price
782     2860
10082   4711
32973    811


In [ ]:
from sklearn.metrics import r2_score

# Assuming 'model' is your trained Keras model, 'Xtest' is your test data, and 'ytest' are the true target values
print (f"{Xtrain.shape=}")

# Convert Xtrain to PyTorch tensor
Xtrain_tensor = torch.tensor(Xtrain.values, dtype=torch.float32)
y_predicted = model(Xtrain_tensor)

# Convert predictions back to numpy array for r2_score
y_predicted = y_predicted.detach().numpy()
r2 = r2_score(ytrain, y_predicted)
print("R-squared Train:", r2)

# Convert Xtest to PyTorch tensor
Xtest_tensor = torch.tensor(Xtest.values, dtype=torch.float32)
y_predicted = model(Xtest_tensor)

# Convert predictions back to numpy array for r2_score
y_predicted = y_predicted.detach().numpy()
r2 = r2_score(ytest, y_predicted)
print("R-squared Test:", r2)

Xtrain.shape=(37758, 6)
R-squared Train: 0.8771908974385489
R-squared Test: 0.8777515290649166


# Now full pyTorch API

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define the model structure using a class
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(6, 256)
        self.fc2 = nn.Linear(256, 128)
        self.fc3 = nn.Linear(128, 64)
        self.fc4 = nn.Linear(64, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = torch.relu(self.fc3(x))
        x = self.fc4(x)
        return x

# Create an instance of the model
model = Net()

# Define the optimizer and loss function
optimizer = optim.Adam(model.parameters())
criterion = nn.MSELoss()

In [ ]:
# Convert data to PyTorch tensors
Xtrain_tensor = torch.tensor(Xtrain.values, dtype=torch.float32)
ytrain_tensor = torch.tensor(ytrain.values, dtype=torch.float32)

# Train the model
epochs = 130
batch_size = 100

start_time = time.time()
for epoch in range(epochs):
  for i in range(0, len(Xtrain_tensor), batch_size):
    # Get batch of data
    Xbatch = Xtrain_tensor[i:i+batch_size]
    ybatch = ytrain_tensor[i:i+batch_size]

    # Forward pass
    outputs = model(Xbatch)
    loss = criterion(outputs, ybatch)

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
  if ((epoch+1)%10==0):
    end_time = time.time()
    elapsed_time = end_time - start_time
    print(f"Training time ({epoch+1}): {elapsed_time=} seconds")
end_time = time.time()
elapsed_time = end_time - start_time
print(f"Training time ({epoch+1}): {elapsed_time=} seconds")


In [ ]:
from sklearn.metrics import r2_score

# Assuming 'model' is your trained PyTorch model, 'Xtest' is your test data, and 'ytest' are the true target values
print (f"{Xtrain.shape=}")

# Convert Xtrain to PyTorch tensor
Xtrain_tensor = torch.tensor(Xtrain.values, dtype=torch.float32)
y_predicted = model(Xtrain_tensor)

# Convert predictions back to numpy array for r2_score
y_predicted = y_predicted.detach().numpy()
r2 = r2_score(ytrain, y_predicted)
print("R-squared Train:", r2)

# Convert Xtest to PyTorch tensor
Xtest_tensor = torch.tensor(Xtest.values, dtype=torch.float32)
y_predicted = model(Xtest_tensor)

# Convert predictions back to numpy array for r2_score
y_predicted = y_predicted.detach().numpy()
r2 = r2_score(ytest, y_predicted)
print("R-squared Test:", r2)

Xtrain.shape=(37758, 6)
R-squared Train: 0.8821964244680871
R-squared Test: 0.881390009647816


# Now Tensorflow API

In [11]:
import tensorflow as tf
import time

# Define the model structure using TensorFlow and tf.Variable
class Net(tf.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.w1 = tf.Variable(tf.random.normal([6, 256]))
    self.b1 = tf.Variable(tf.zeros([256]))
    self.w2 = tf.Variable(tf.random.normal([256, 128]))
    self.b2 = tf.Variable(tf.zeros([128]))
    self.w3 = tf.Variable(tf.random.normal([128, 64]))
    self.b3 = tf.Variable(tf.zeros([64]))
    self.w4 = tf.Variable(tf.random.normal([64, 1]))
    self.b4 = tf.Variable(tf.zeros([1]))

  def __call__(self, x):
    x = tf.nn.relu(tf.matmul(x, self.w1) + self.b1)
    x = tf.nn.relu(tf.matmul(x, self.w2) + self.b2)
    x = tf.nn.relu(tf.matmul(x, self.w3) + self.b3)
    x = tf.matmul(x, self.w4) + self.b4
    return x

# Create an instance of the model
model = Net()

# Define the optimizer and loss function
optimizer = tf.keras.optimizers.Adam()
criterion = tf.keras.losses.MeanSquaredError()

# Convert data to TensorFlow tensors
Xtrain_tensor = tf.convert_to_tensor(Xtrain.values, dtype=tf.float32)
ytrain_tensor = tf.convert_to_tensor(ytrain.values, dtype=tf.float32)

# Train the model
epochs = 20
batch_size = 100

start_time = time.time()
for epoch in range(epochs):
  for i in range(0, len(Xtrain_tensor), batch_size):
    # Get batch of data
    Xbatch = Xtrain_tensor[i:i+batch_size]
    ybatch = ytrain_tensor[i:i+batch_size]

    with tf.GradientTape() as tape:
      # Forward pass
      outputs = model(Xbatch)
      loss = criterion(ybatch, outputs)  # Calculate loss within GradientTape context

    # Backward pass and optimization
    gradients = tape.gradient(loss, model.trainable_variables)
    if gradients:
        optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    else:
        print("No gradients to apply")
        break
  if ((epoch+1)%10==0):
    end_time = time.time()
    elapsed_time = end_time - start_time
    print(f"Training time ({epoch+1}): {elapsed_time=} seconds")
end_time = time.time()
elapsed_time = end_time - start_time
print(f"Training time ({epoch+1}): {elapsed_time=} seconds")


Training time (10): elapsed_time=150.23390531539917 seconds
Training time (20): elapsed_time=299.1795496940613 seconds
Training time (20): elapsed_time=299.17985486984253 seconds


In [12]:
from sklearn.metrics import r2_score

# Assuming 'model' is your trained TensorFlow model, 'Xtest' is your test data, and 'ytest' are the true target values
print (f"{Xtrain.shape=}")

# Convert Xtrain to TensorFlow tensor
Xtrain_tensor = tf.convert_to_tensor(Xtrain.values, dtype=tf.float32)
y_predicted = model(Xtrain_tensor)

# Convert predictions back to numpy array for r2_score
y_predicted = y_predicted.numpy()
r2 = r2_score(ytrain, y_predicted)
print("R-squared Train:", r2)

# Convert Xtest to TensorFlow tensor
Xtest_tensor = tf.convert_to_tensor(Xtest.values, dtype=tf.float32)
y_predicted = model(Xtest_tensor)

# Convert predictions back to numpy array for r2_score
y_predicted = y_predicted.numpy()
r2 = r2_score(ytest, y_predicted)
print("R-squared Test:", r2)

Xtrain.shape=(37758, 6)
R-squared Train: 0.8756208460116558
R-squared Test: 0.8768909892161543


# Now with GPU

In [13]:
import tensorflow as tf
import time

# Explicitly request a GPU if available
with tf.device('/device:GPU:0'):  # Will fall back to CPU if no GPU is found

  # Define the model structure using TensorFlow and tf.Variable
  class Net(tf.Module):
    def __init__(self):
      super(Net, self).__init__()
      self.w1 = tf.Variable(tf.random.normal([6, 256]))
      self.b1 = tf.Variable(tf.zeros([256]))
      self.w2 = tf.Variable(tf.random.normal([256, 128]))
      self.b2 = tf.Variable(tf.zeros([128]))
      self.w3 = tf.Variable(tf.random.normal([128, 64]))
      self.b3 = tf.Variable(tf.zeros([64]))
      self.w4 = tf.Variable(tf.random.normal([64, 1]))
      self.b4 = tf.Variable(tf.zeros([1]))

    def __call__(self, x):
      x = tf.nn.relu(tf.matmul(x, self.w1) + self.b1)
      x = tf.nn.relu(tf.matmul(x, self.w2) + self.b2)
      x = tf.nn.relu(tf.matmul(x, self.w3) + self.b3)
      x = tf.matmul(x, self.w4) + self.b4
      return x

  # Create an instance of the model
  model = Net()

  # Define the optimizer and loss function
  optimizer = tf.keras.optimizers.Adam()
  criterion = tf.keras.losses.MeanSquaredError()

  # Convert data to TensorFlow tensors
  Xtrain_tensor = tf.convert_to_tensor(Xtrain.values, dtype=tf.float32)
  ytrain_tensor = tf.convert_to_tensor(ytrain.values, dtype=tf.float32)

  # Train the model
  epochs = 20
  batch_size = 1000

  start_time = time.time()
  for epoch in range(epochs):
    for i in range(0, len(Xtrain_tensor), batch_size):
      # Get batch of data
      Xbatch = Xtrain_tensor[i:i+batch_size]
      ybatch = ytrain_tensor[i:i+batch_size]

      with tf.GradientTape() as tape:
        # Forward pass
        outputs = model(Xbatch)
        loss = criterion(ybatch, outputs)  # Calculate loss within GradientTape context

      # Backward pass and optimization
      gradients = tape.gradient(loss, model.trainable_variables)
      if gradients:
          optimizer.apply_gradients(zip(gradients, model.trainable_variables))
      else:
          print("No gradients to apply")
          break
    if ((epoch+1)%10==0):
      end_time = time.time()
      elapsed_time = end_time - start_time
      print(f"Training time ({epoch+1}): {elapsed_time=} seconds")
  end_time = time.time()
  elapsed_time = end_time - start_time
  print(f"Training time ({epoch+1}): {elapsed_time=} seconds")


Training time (10): elapsed_time=15.160910606384277 seconds
Training time (20): elapsed_time=30.69427752494812 seconds
Training time (20): elapsed_time=30.694395065307617 seconds


In [14]:
from sklearn.metrics import r2_score

# Assuming 'model' is your trained TensorFlow model, 'Xtest' is your test data, and 'ytest' are the true target values
print (f"{Xtrain.shape=}")

# Convert Xtrain to TensorFlow tensor
Xtrain_tensor = tf.convert_to_tensor(Xtrain.values, dtype=tf.float32)
y_predicted = model(Xtrain_tensor)

# Convert predictions back to numpy array for r2_score
y_predicted = y_predicted.numpy()
r2 = r2_score(ytrain, y_predicted)
print("R-squared Train:", r2)

# Convert Xtest to TensorFlow tensor
Xtest_tensor = tf.convert_to_tensor(Xtest.values, dtype=tf.float32)
y_predicted = model(Xtest_tensor)

# Convert predictions back to numpy array for r2_score
y_predicted = y_predicted.numpy()
r2 = r2_score(ytest, y_predicted)
print("R-squared Test:", r2)

Xtrain.shape=(37758, 6)
R-squared Train: 0.8700311662488012
R-squared Test: 0.8715327263234984
